
import evdev

# Map evdev keycode to HID usage code
# Based on USB HID Usage Tables
# https://usb.org/sites/default/files/hut1_2.pdf (Page 53)

EVDEV_TO_HID = {
    evdev.ecodes.KEY_A: 0x04,
    evdev.ecodes.KEY_B: 0x05,
    evdev.ecodes.KEY_C: 0x06,
    evdev.ecodes.KEY_D: 0x07,
    evdev.ecodes.KEY_E: 0x08,
    evdev.ecodes.KEY_F: 0x09,
    evdev.ecodes.KEY_G: 0x0A,
    evdev.ecodes.KEY_H: 0x0B,
    evdev.ecodes.KEY_I: 0x0C,
    evdev.ecodes.KEY_J: 0x0D,
    evdev.ecodes.KEY_K: 0x0E,
    evdev.ecodes.KEY_L: 0x0F,
    evdev.ecodes.KEY_M: 0x10,
    evdev.ecodes.KEY_N: 0x11,
    evdev.ecodes.KEY_O: 0x12,
    evdev.ecodes.KEY_P: 0x13,
    evdev.ecodes.KEY_Q: 0x14,
    evdev.ecodes.KEY_R: 0x15,
    evdev.ecodes.KEY_S: 0x16,
    evdev.ecodes.KEY_T: 0x17,
    evdev.ecodes.KEY_U: 0x18,
    evdev.ecodes.KEY_V: 0x19,
    evdev.ecodes.KEY_W: 0x1A,
    evdev.ecodes.KEY_X: 0x1B,
    evdev.ecodes.KEY_Y: 0x1C,
    evdev.ecodes.KEY_Z: 0x1D,
    evdev.ecodes.KEY_1: 0x1E,
    evdev.ecodes.KEY_2: 0x1F,
    evdev.ecodes.KEY_3: 0x20,
    evdev.ecodes.KEY_4: 0x21,
    evdev.ecodes.KEY_5: 0x22,
    evdev.ecodes.KEY_6: 0x23,
    evdev.ecodes.KEY_7: 0x24,
    evdev.ecodes.KEY_8: 0x25,
    evdev.ecodes.KEY_9: 0x26,
    evdev.ecodes.KEY_0: 0x27,
    evdev.ecodes.KEY_ENTER: 0x28,
    evdev.ecodes.KEY_ESC: 0x29,
    evdev.ecodes.KEY_BACKSPACE: 0x2A,
    evdev.ecodes.KEY_TAB: 0x2B,
    evdev.ecodes.KEY_SPACE: 0x2C,
    evdev.ecodes.KEY_MINUS: 0x2D,
    evdev.ecodes.KEY_EQUAL: 0x2E,
    evdev.ecodes.KEY_LEFTBRACE: 0x2F,
    evdev.ecodes.KEY_RIGHTBRACE: 0x30,
    evdev.ecodes.KEY_BACKSLASH: 0x31,
    evdev.ecodes.KEY_SEMICOLON: 0x33,
    evdev.ecodes.KEY_APOSTROPHE: 0x34,
    evdev.ecodes.KEY_GRAVE: 0x35,
    evdev.ecodes.KEY_COMMA: 0x36,
    evdev.ecodes.KEY_DOT: 0x37,
    evdev.ecodes.KEY_SLASH: 0x38,
    evdev.ecodes.KEY_CAPSLOCK: 0x39,
    evdev.ecodes.KEY_F1: 0x3A,
    evdev.ecodes.KEY_F2: 0x3B,
    evdev.ecodes.KEY_F3: 0x3C,
    evdev.ecodes.KEY_F4: 0x3D,
    evdev.ecodes.KEY_F5: 0x3E,
    evdev.ecodes.KEY_F6: 0x3F,
    evdev.ecodes.KEY_F7: 0x40,
    evdev.ecodes.KEY_F8: 0x41,
    evdev.ecodes.KEY_F9: 0x42,
    evdev.ecodes.KEY_F10: 0x43,
    evdev.ecodes.KEY_F11: 0x44,
    evdev.ecodes.KEY_F12: 0x45,
    evdev.ecodes.KEY_LEFT: 0x50,
    evdev.ecodes.KEY_RIGHT: 0x4F,
    evdev.ecodes.KEY_UP: 0x52,
    evdev.ecodes.KEY_DOWN: 0x51,
}

MODIFIER_MAP = {
    evdev.ecodes.KEY_LEFTCTRL: 0x01,
    evdev.ecodes.KEY_LEFTSHIFT: 0x02,
    evdev.ecodes.KEY_LEFTALT: 0x04,
    evdev.ecodes.KEY_LEFTMETA: 0x08,
    evdev.ecodes.KEY_RIGHTCTRL: 0x10,
    evdev.ecodes.KEY_RIGHTSHIFT: 0x20,
    evdev.ecodes.KEY_RIGHTALT: 0x40,
    evdev.ecodes.KEY_RIGHTMETA: 0x80,
}
